### ISSUE TITLE
Unordered list

### ISSUE THREAD

**Issue by amitdagar** [jamesrochabrun/CoreDataTutorialPart1Final#1]
hi,
i am not getting the solution that, why data is set in table view in Unordered list.When i hit the API to the web browser i got the response in exact order what it is, but when i get the the json and save to the local DB and fetch it the data is not in same order as json response.
Please do the needful, and suggest me the answer.

**Comment by jamesrochabrun** [comment]
@amitdagar So sorry for the late response I assume that by now you already found why that happened when getting the values from the database it's like getting values from a hash table so they will be returned unordered you can solve this by passing a sort descriptor defining how you want to order them.
